server:
  port: 8080
  servlet:
    context-path: /perm-menu-manager/api

spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:2881/sit_ebpm_ebbe_global
          username: root
          password: NJcb@1234.
          driver-class-name: com.mysql.cj.jdbc.Driver
        second:
          url: jdbc:mysql://127.0.0.1:2881/sit2_ebpm_ebbe_global
          username: root
          password: NJcb@1234.
          driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  file:
    name: perm-menu-manager.log
  level:
    root: info
    com.example.permmenu.mapper: debug
